In [2]:
import pandas as pd
import numpy as np
# Dataset load 
df = pd.read_csv(r"C:\Users\vinod\Downloads\Patient_Data.csv")
df = pd.read_csv(r"‪C:\Users\vinod\Downloads\Billing_Data.csv")

# Dataset 
df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [3]:
## 1.Load the patient dataset and show summary with info().
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [4]:
# 2.Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
# Select only billing-related columns
billing_df = df[['PatientID', 'Department', 'Doctor', 'BillAmount']]

billing_df.head()

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

In [5]:
# 3.Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
df = df.drop(columns=['ReceptionistID', 'CheckInTime'])

print(df)

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [6]:
# 4.Use groupby to find total bill amount per department.
total_bill_per_dept = df.groupby('Department')['BillAmount'].sum().reset_index()

print(total_bill_per_dept)

    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

In [7]:
# 5.Remove duplicate patient records based on PatientID.
df = df.drop_duplicates(subset=['PatientID'], keep='first')

print(df)

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [25]:
# 6.Fill missing BillAmount values with the mean bill amount.
mean_bill = df['BillAmount'].mean()

# Fill missing values with the mean
df['BillAmount'] = df['BillAmount'].fillna(mean_bill)

print(df)

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [26]:
# 7.Merge the billing dataset with patient dataset on PatientID.
import pandas as pd


# Merge datasets on PatientID
merged_df = pd.merge(patients, billing, on='PatientID')

print(merged_df)

   PatientID     Name   Department  BillAmount PaymentStatus
0        101    Alice   Cardiology        5000          Paid
1        102      Bob    Neurology         400        Unpaid
2        103  Charlie  Orthopedics        7500          Paid
3        104    David   Cardiology        6200          Paid

In [32]:
# 8.Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
# Concatenate row-wise

new_patients = pd.DataFrame({
    'PatientID': [105, 106],
    'Name': ['dhanshri', 'vinod'],
    'Department': ['Neurology', 'Cardiology']
})
updated_patients = pd.concat([patients, new_patients], ignore_index=True)

print(updated_patients)

   PatientID      Name   Department
0        101     Alice   Cardiology
1        102       Bob    Neurology
2        103   Charlie  Orthopedics
3        104     David   Cardiology
4        105  dhanshri    Neurology
5        106     vinod   Cardiology

In [37]:
# 9.Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

new_columns = pd.DataFrame({
    'InsuranceCovered': [300, 00, 150, 250],
    'FinalAmount': [200, 00, 150, 200]
})

# Concatenate column-wise

updated_billing = pd.concat([billing, new_columns], axis=1)

print(updated_billing)

   PatientID  BillAmount PaymentStatus  InsuranceCovered  FinalAmount
0        101        5000          Paid               300          200
1        102         400        Unpaid                 0            0
2        103        7500          Paid               150          150
3        104        6200          Paid               250          200

In [40]:
print("Final Cleaned Dataset:\n" )
print("\nDepartment-wise Revenue:\n")

Final Cleaned Dataset:


Department-wise Revenue:

In [ ]:
###### FINISH  ####