In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\vinod\Downloads\amazon review file .csv", encoding='Windows-1252')

In [4]:
df.head()

  label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [5]:
df.describe()

        label                                             review
count   10000                                              10000
unique      2                                              10000
top       neg  Stuning even for the non-gamer: This sound tra...
freq     5097                                                  1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   10000 non-null  object
 1   review  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB

In [7]:
df.isnull().sum

<bound method DataFrame.sum of       label  review
0     False   False
1     False   False
2     False   False
3     False   False
4     False   False
...     ...     ...
9995  False   False
9996  False   False
9997  False   False
9998  False   False
9999  False   False

[10000 rows x 2 columns]>

In [8]:
print(df.columns)

Index(['label', 'review'], dtype='object')

In [9]:
print(df['review'].count())

10000

In [10]:
all = " ".join(df['review'].dropna().tolist())
print(all[:1000])

Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^ The best soundtrack ever to anything.: I'm reading a lot of reviews saying that this is the best 'game soundtrack' and I figured that I'd write a review to disagree a bit. This in my opinino is Yasunori Mitsuda's ultimate masterpiece. The music is timeless and I'm been listening to it for years now and its beauty simply refuses to fade.The price tag on this is pretty staggering I must say, but if you are going to buy any cd for this much money, this is the only one that I feel would be worth every penny. Amazing!: This soundtrack is my favorite music of all time, han

In [11]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [12]:
df = pd.read_csv(r"C:\Users\vinod\Downloads\amazon review file .csv", encoding='Windows-1252')

In [13]:
df

     label                                             review
0      pos  Stuning even for the non-gamer: This sound tra...
1      pos  The best soundtrack ever to anything.: I'm rea...
2      pos  Amazing!: This soundtrack is my favorite music...
3      pos  Excellent Soundtrack: I truly like this soundt...
4      pos  Remember, Pull Your Jaw Off The Floor After He...
...    ...                                                ...
9995   pos  A revelation of life in small town America in ...
9996   pos  Great biography of a very interesting journali...
9997   neg  Interesting Subject; Poor Presentation: You'd ...
9998   neg  Don't buy: The box looked used and it is obvio...
9999   pos  Beautiful Pen and Fast Delivery.: The pen was ...

[10000 rows x 2 columns]

In [14]:
data = {
    "label": ["pos","pos","pos","neg"],
    "review": [
        "Amazing soundtrack I love it",
        "Great book very interesting",
        "Worst product ever",
        "Bad quality waste of money"
    ]
}

df = pd.DataFrame(data)

In [15]:
df

  label                        review
0   pos  Amazing soundtrack I love it
1   pos   Great book very interesting
2   pos            Worst product ever
3   neg    Bad quality waste of money

In [16]:

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    return text

sample_text = "Stuning even for the non-gamer: This sound track was beautiful! 123"
cleaned = clean_text(sample_text)
print(cleaned)

stuning even for the non gamer  this sound track was beautiful

In [17]:
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vinod\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [18]:
df['review'] = df['review'].apply(clean_text)
df['review'] = df['review'].apply(remove_stopwords)

In [19]:
df['label'] = df['label'].map({'pos':1, 'neg':0})

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    df['review'], df['label'], test_size=0.2, random_state=42
)

In [21]:
vectorizer = TfidfVectorizer(max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Drop rows with missing labels
df = df.dropna(subset=['label'])

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    df['review'], df['label'], test_size=0.2, random_state=42
)

# Vectorize text
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train model
model = LogisticRegression(max_iter=500)
model.fit(X_train_vec, y_train)

print("Model trained successfully!")

Model trained successfully!

In [23]:
y_pred = model.predict(X_test_vec)

In [24]:
df = df.dropna(subset=['label','review'])

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['label'], df['review'], test_size=0.2, random_state=42
)

In [52]:
X = df['review']   # input text
y = df['label']          # output label (pos/neg)

In [53]:
from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         1

    accuracy                           1.00         1
   macro avg       1.00      1.00      1.00         1
weighted avg       1.00      1.00      1.00         1

In [ ]:
sample = ["This product is amazing and very useful"]

sample = [clean_text(s) for s in sample]
sample = [remove_stopwords(s) for s in sample]

sample_vec = vectorizer.transform(sample)

prediction = model.predict(sample_vec)

print("Positive" if prediction[0]==1 else "Negative")

In [45]:
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("F1 Score:", f1_score(y_test, y_pred_lr, pos_label='pos'))

Logistic Regression
Accuracy: 1.0
F1 Score: 0.0

C:\Users\vinod\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [46]:
X = df['review']   # cleaned text
y = df['label']

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(X)

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [49]:
from sklearn.metrics import f1_score
svm_model = SVC()
svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

print("\nSVM Model")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("F1 Score:", f1_score(y_test, y_pred_svm, pos_label='pos'))

SVM Model
Accuracy: 1.0
F1 Score: 0.0

C:\Users\vinod\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [50]:
from sklearn.neural_network import MLPClassifier
nn_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=300)
nn_model.fit(X_train, y_train)

y_pred_nn = nn_model.predict(X_test)

print("\nNeural Network")
print("Accuracy:", accuracy_score(y_test, y_pred_nn))
print("F1 Score:", f1_score(y_test, y_pred_nn, pos_label='pos'))

Neural Network
Accuracy: 1.0
F1 Score: 0.0

C:\Users\vinod\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\vinod\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

# model train
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)

# prediction (IMPORTANT 🔥)
y_pred_lr = lr_model.predict(X_test)

# evaluation
print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("F1 Score:", f1_score(y_test, y_pred_lr, pos_label='pos'))

Logistic Regression
Accuracy: 1.0
F1 Score: 0.0

C:\Users\vinod\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

# Sentiment Analysis of Reviews
## 1. Introduction

Sentiment Analysis is the process of determining the emotional tone behind a body of text. It helps understand whether a piece of text expresses a positive, negative, or neutral sentiment.

Problem Statement:
We aim to analyze customer reviews and classify them into positive or negative sentiments. This will help businesses understand customer opinions automatically and at scale.

# 2. Data Preprocessing

Before training the model, the text data needs to be cleaned and standardized:

Converted all text to lowercase to avoid case-sensitive differences.
Removed special characters, numbers, and punctuation to focus on meaningful words.
Removed missing values (NaN) to avoid errors during training.
Optionally, stopwords and stemming/lemmatization can be applied to improve performance.

This ensures that the input text is consistent and ready for vectorization

# 3. Exploratory Data Analysis (EDA)
Counted the number of positive vs negative reviews to check class balance.
Visualized the distribution of sentiments (bar chart/pie chart recommended).

This step helps understand the dataset and ensures that the model is not biased toward one class.

# 4. Model

We used TF-IDF (Term Frequency-Inverse Document Frequency) to convert text into numerical vectors. TF-IDF gives higher weight to important words and reduces the impact of common words.

Model Choice: Logistic Regression

Simple, fast, and effective for text classification.
Works well with high-dimensional sparse data from TF-IDF vectors.

# After training the model on the preprocessed dataset:

Accuracy: ~XX% (replace with your value)
F1-score: ~XX% (replace with your value)

The classification report shows precision, recall, and F1-score for each class.

#  Conclusion
The Logistic Regression model with TF-IDF vectors performs reasonably well in classifying sentiments.
Possible improvements:
Use advanced models like BERT, RoBERTa, or LSTM networks for better contextual understanding.
Apply hyperparameter tuning for TF-IDF and the model.
Handle class imbalance with oversampling/undersampling if needed.

# Final Summary:
This project demonstrates a basic sentiment analysis pipeline: cleaning text, vectorizing with TF-IDF, training a Logistic Regression classifier, and evaluating performance. The model provides a good starting point for analyzing reviews automatically and can be further improved with modern NLP techniques.